//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDemo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeedback
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Number { get; set; }
        public int IDANumber { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public int Grade { get; set; }
    }
}
